language: python
python:
- '3.6'

branches:
  only:
  - master

addons:
  apt:
    packages:
      - rsync
      - openssh-client

install:
  - pip install -r requirements.txt

script: pelican content

after_success:
  - 'if [ ${TRAVIS_SECURE_ENV_VARS} = "true" ]; then
       openssl aes-256-cbc -K $encrypted_a9942967d0d9_key -iv $encrypted_a9942967d0d9_iv -in travis_access.enc -out travis_access -d || travis_terminate 1;
       eval $(ssh-agent -s) || travis_terminate 1;
       chmod 600 travis_access && ssh-add travis_access || travis_terminate 1;
       mkdir -p ~/.ssh || travis_terminate 1;
       echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config || travis_terminate 1;
       rsync -avz --delete output/ $DEPLOYMENT_URL || travis_terminate 1;
    fi'
