language: python
python:
- '3.6'

branches:
  only:
  - master

addons:
  apt:
    packages:
      - rsync
      - openssh-client
before_install:
- openssl aes-256-cbc -K $encrypted_a9942967d0d9_key -iv $encrypted_a9942967d0d9_iv -in travis_access.enc -out travis_access -d

install:
  - pip install -r requirements.txt
  - eval $(ssh-agent -s)
  - chmod 600 travis_access && ssh-add travis_access
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
script: pelican content

after_success:
  - rsync -avz --delete output/ $DEPLOYMENT_URL

